import { IMutualiste } from "src/app/models/mutualiste";

export const mockMutualistes: IMutualiste[] = [
    {
      idMutualiste: 1,
      matriculeMutualiste: "MAT001",
      categorieMutualiste: "Categorie A",
      serviceMutualiste: "Service X",
      fonctionMutualiste: "Fonction Y",
      depensesSante: 500,
      idAssure: 1001,
      nomAssure: "Dupont",
      prenomAssure: "Jean",
      dateNaissanceAssure: new Date("1980-01-01"),
      sexeAssure: "M",
      adresseAssure: "123 Rue de la Paix",
      telephoneAssure: "0102030405",
      statutAssure: true,
      photoAssure: "photo1.jpg"
    },

    /*
    {
      idMutualiste: 2,
      matriculeMutualiste: "MAT002",
      categorieMutualiste: "Categorie B",
      serviceMutualiste: "Service Y",
      fonctionMutualiste: "Fonction Z",
      depensesSante: 750,
      idAssure: 1002,
      nom: "Martin",
      prenom: "Sophie",
      dateNaiss: new Date("1990-02-02"),
      sexe: "F",
      adress: "456 Avenue des Champs",
      tel: "0203040506",
      status: false,
      photo: "photo2.jpg"
    },
    {
      idMutualiste: 3,
      matriculeMutualiste: "MAT003",
      categorieMutualiste: "Categorie C",
      serviceMutualiste: "Service Z",
      fonctionMutualiste: "Fonction A",
      depensesSante: 600,
      idAssure: 1003,
      nom: "Durand",
      prenom: "Luc",
      dateNaiss: new Date("1975-03-03"),
      sexe: "M",
      adress: "789 Boulevard Saint-Germain",
      tel: "0304050607",
      status: true,
      photo: "photo3.jpg"
    },
    {
      idMutualiste: 4,
      matriculeMutualiste: "MAT004",
      categorieMutualiste: "Categorie D",
      serviceMutualiste: "Service A",
      fonctionMutualiste: "Fonction B",
      depensesSante: 800,
      idAssure: 1004,
      nom: "Petit",
      prenom: "Marie",
      dateNaiss: new Date("1985-04-04"),
      sexe: "F",
      adress: "101 Rue de Rivoli",
      tel: "0405060708",
      status: false,
      photo: "photo4.jpg"
    },
    {
      idMutualiste: 5,
      matriculeMutualiste: "MAT005",
      categorieMutualiste: "Categorie E",
      serviceMutualiste: "Service B",
      fonctionMutualiste: "Fonction C",
      depensesSante: 450,
      idAssure: 1005,
      nom: "Lefevre",
      prenom: "Emma",
      dateNaiss: new Date("1995-05-05"),
      sexe: "F",
      adress: "202 Place de la Concorde",
      tel: "0506070809",
      status: true,
      photo: "photo5.jpg"
    },
    {
      idMutualiste: 6,
      matriculeMutualiste: "MAT006",
      categorieMutualiste: "Categorie F",
      serviceMutualiste: "Service C",
      fonctionMutualiste: "Fonction D",
      depensesSante: 700,
      idAssure: 1006,
      nom: "Moreau",
      prenom: "Paul",
      dateNaiss: new Date("1988-06-06"),
      sexe: "M",
      adress: "303 Rue de la Republique",
      tel: "0607080901",
      status: false,
      photo: "photo6.jpg"
    },
    {
      idMutualiste: 7,
      matriculeMutualiste: "MAT007",
      categorieMutualiste: "Categorie G",
      serviceMutualiste: "Service D",
      fonctionMutualiste: "Fonction E",
      depensesSante: 550,
      idAssure: 1007,
      nom: "Girard",
      prenom: "Laura",
      dateNaiss: new Date("1992-07-07"),
      sexe: "F",
      adress: "404 Avenue Victor Hugo",
      tel: "0708090102",
      status: true,
      photo: "photo7.jpg"
    },
    {
      idMutualiste: 8,
      matriculeMutualiste: "MAT008",
      categorieMutualiste: "Categorie H",
      serviceMutualiste: "Service E",
      fonctionMutualiste: "Fonction F",
      depensesSante: 600,
      idAssure: 1008,
      nom: "Garcia",
      prenom: "Antoine",
      dateNaiss: new Date("1983-08-08"),
      sexe: "M",
      adress: "505 Boulevard Voltaire",
      tel: "0809010203",
      status: false,
      photo: "photo8.jpg"
    },
    {
      idMutualiste: 9,
      matriculeMutualiste: "MAT009",
      categorieMutualiste: "Categorie I",
      serviceMutualiste: "Service F",
      fonctionMutualiste: "Fonction G",
      depensesSante: 650,
      idAssure: 1009,
      nom: "Bernard",
      prenom: "Isabelle",
      dateNaiss: new Date("1979-09-09"),
      sexe: "F",
      adress: "606 Rue du Faubourg Saint-Honoré",
      tel: "0901020304",
      status: true,
      photo: "photo9.jpg"
    },
    {
      idMutualiste: 10,
      matriculeMutualiste: "MAT010",
      categorieMutualiste: "Categorie J",
      serviceMutualiste: "Service G",
      fonctionMutualiste: "Fonction H",
      depensesSante: 700,
      idAssure: 1010,
      nom: "Rousseau",
      prenom: "Pierre",
      dateNaiss: new Date("1981-10-10"),
      sexe: "M",
      adress: "707 Avenue des Ternes",
      tel: "1012030405",
      status: false,
      photo: "photo10.jpg"
    }
      */
  ];
